import React, { createContext, useContext, useState, useEffect } from 'react';

export type LanguageCode = 'en' | 'hi' | 'as' | 'bn' | 'mni' | 'khasi' | 'mizo' | 'nagamese' | 'ne';

export interface LanguageInfo {
  code: LanguageCode;
  label: string;
  native: string;
  states: string;
  script: string;
}

export const SUPPORTED_LANGUAGES: LanguageInfo[] = [
  { code: 'en', label: 'English', native: 'English', states: 'All 8 States (Official)', script: 'Latin' },
  { code: 'hi', label: 'Hindi', native: 'हिन्दी', states: 'All 8 States (National)', script: 'Devanagari' },
  { code: 'as', label: 'Assamese', native: 'অসমীয়া', states: 'Assam', script: 'Bengali-Assamese' },
  { code: 'bn', label: 'Bengali', native: 'বাংলা', states: 'Tripura, Assam (Barak)', script: 'Bengali' },
  { code: 'mni', label: 'Meitei (Manipuri)', native: 'ꯃꯩꯇꯩꯂꯣꯟ', states: 'Manipur', script: 'Meitei Mayek' },
  { code: 'khasi', label: 'Khasi / Garo', native: 'Khasi / Garo', states: 'Meghalaya', script: 'Latin' },
  { code: 'mizo', label: 'Mizo', native: 'Mizo ṭawng', states: 'Mizoram', script: 'Latin' },
  { code: 'nagamese', label: 'Nagamese', native: 'Nagamese', states: 'Nagaland', script: 'Latin' },
  { code: 'ne', label: 'Nepali', native: 'नेपाली', states: 'Sikkim', script: 'Devanagari' },
];

const UI_STRINGS: Record<LanguageCode, Record<string, string>> = {
  en: {
    app_title: "NERALIS — North Eastern Logistics Intelligence",
    tagline: "Ministry of Development of North Eastern Region (MDoNER)",
    module_1: "Accessibility Monitoring",
    module_2: "AI Route Optimizer",
    module_3: "Vehicle & Fleet Tracking",
    module_4: "Predictive Disruption (72h)",
    module_5: "Multilingual Alert Center",
    module_6: "Field Reporting PWA",
    module_7: "Central Analytics Dashboard",
    module_8: "Offline & Resilience",
    operations: "Operations",
    response: "Response",
    insights: "Insights",
    reports_compliance: "Reports & Compliance",
    parliament_report: "Parliament / MLA Brief",
    today_alerts: "Active Alerts",
    open_routes_pct: "Open Corridors",
    vehicles_tracked: "Tracked Fleet",
    pending_reports: "Pending Reports",
    sync_status: "Network Mode",
    online: "Online (5G / Fiber)",
    low_2g: "Low 2G Bandwidth",
    offline: "Offline Storage Active",
    quick_search: "Search 89 NER districts, highways, or bridge sensors...",
    emergency_ticker: "ALERT: Teesta Valley NH-10 closed at 29th Mile. Brahmaputra NW-2 Ro-Ro barge active for essential medical transport.",
    export_pdf: "Export PDF",
    export_excel: "Export Excel",
    export_csv: "Export CSV",
    filter: "Filter",
    status_open: "Open",
    status_restricted: "Restricted",
    status_degraded: "Degraded",
    status_closed: "Closed",
    role: "User Role",
    admin: "State Admin (MDoNER)",
    collector: "District Collector / DM",
    logistics: "Logistics Operator",
    inspector: "Field Inspector / PWD",
    sign_in: "Sign In",
    register: "Register",
    back_to_map: "← Back to Map",
    one_tap_sos: "ONE-TAP SATELLITE SOS",
    launch_ar: "Launch AR LiDAR",
    submit_report: "Step 5: Submit Ground Report"
  },
  hi: {
    app_title: "नेरालिस — उत्तर पूर्वी लॉजिस्टिक्स इंटेलिजेंस",
    tagline: "उत्तर पूर्वी क्षेत्र विकास मंत्रालय (MDoNER)",
    module_1: "सड़क सुलभता निगरानी",
    module_2: "एआई रूट ऑप्टिमाइज़र",
    module_3: "वाहन व बेड़ा ट्रैकिंग",
    module_4: "पूर्वानुमान व्यवधान (72 घंटे)",
    module_5: "बहुभाषी अलर्ट केंद्र",
    module_6: "फील्ड रिपोर्टिंग PWA",
    module_7: "केंद्रीय एनालिटिक्स डैशबोर्ड",
    module_8: "ऑफलाइन व कनेक्टिविटी",
    operations: "संचालन",
    response: "प्रतिक्रिया व चेतावनी",
    insights: "विश्लेषण व अंतर्दृष्टि",
    reports_compliance: "रिपोर्ट और अनुपालन",
    parliament_report: "संसद / विधायक रिपोर्ट",
    today_alerts: "सक्रिय अलर्ट",
    open_routes_pct: "खुले मार्ग",
    vehicles_tracked: "सक्रिय वाहन",
    pending_reports: "लंबित रिपोर्ट",
    sync_status: "नेटवर्क मोड",
    online: "ऑनलाइन (5G)",
    low_2g: "धीमा 2G नेटवर्क",
    offline: "ऑफलाइन सक्रिय",
    quick_search: "89 पूर्वोत्तर जिलों, राजमार्गों या पुलों को खोजें...",
    emergency_ticker: "सूचना: तीस्ता घाटी NH-10 29वें मील पर बंद। ब्रह्मपुत्र जलमार्ग रो-रो सेवा आवश्यक दवाओं हेतु चालू।",
    export_pdf: "पीडीएफ निर्यात",
    export_excel: "एक्सेल निर्यात",
    export_csv: "सीएसवी निर्यात",
    filter: "फ़िल्टर",
    status_open: "खुला",
    status_restricted: "प्रतिबंधित",
    status_degraded: "खराब",
    status_closed: "बंद",
    role: "भूमिका",
    admin: "राज्य प्रशासन (MDoNER)",
    collector: "जिलाधिकारी (DM)",
    logistics: "लॉजिस्टिक्स ऑपरेटर",
    inspector: "फील्ड इंस्पेक्टर (PWD)",
    sign_in: "लॉग इन करें",
    register: "पंजीकरण",
    back_to_map: "← मुख्य मानचित्र",
    one_tap_sos: "आपातकालीन सैटेलाइट एसओएस",
    launch_ar: "एआर लिडार चालू करें",
    submit_report: "चरण 5: रिपोर्ट दर्ज करें"
  },
  as: {
    app_title: "নেৰালিচ — উত্তৰ-পূব লজিষ্টিকছ ইন্টেলিজেন্স",
    tagline: "উত্তৰ-পূব অঞ্চল উন্নয়ন মন্ত্ৰালয় (MDoNER)",
    module_1: "পথ সুগমতা নিৰীক্ষণ",
    module_2: "AI পথ অনুকূলকৰণ",
    module_3: "যান-বাহন ট্ৰেকিং",
    module_4: "বাধাৰ পূৰ্বানুমান (৭২ ঘণ্টা)",
    module_5: "বহুভাষিক সতৰ্কতা কেন্দ্ৰ",
    module_6: "ক্ষেত্ৰ প্ৰতিবেদন PWA",
    module_7: "কেন্দ্ৰীয় বিশ্লেষণ ডেশ্ববৰ্ড",
    module_8: "অফলাইন আৰু নেটৱৰ্ক",
    operations: "পৰিচালনা",
    response: "সঁহাৰি আৰু সতৰ্কতা",
    insights: "তথ্য বিশ্লেষণ",
    reports_compliance: "প্ৰতিবেদন আৰু নিয়ম",
    parliament_report: "সংসদ / বিধায়ক প্ৰতিবেদন",
    today_alerts: "সক্ৰিয় সতৰ্কতা",
    open_routes_pct: "খোলা পথ",
    vehicles_tracked: "ট্ৰেক কৰা গাড়ী",
    pending_reports: "বাকী থকা প্ৰতিবেদন",
    sync_status: "নেটৱৰ্ক অৱস্থা",
    online: "অনলাইন (5G)",
    low_2g: "ধীৰ 2G সংযোগ",
    offline: "অফলাইন সক্ৰিয়",
    quick_search: "৮৯খন জিলা, ঘাইপথ বা দলং বিচাৰক...",
    emergency_ticker: "সতৰ্কতা: তিস্তা উপত্যকা NH-10 বন্ধ। ব্ৰহ্মপুত্ৰ ৰো-ৰো জাহাজ সেৱা সক্ৰিয়।",
    export_pdf: "PDF ৰপ্তানি",
    export_excel: "Excel ৰপ্তানি",
    export_csv: "CSV ৰপ্তানি",
    filter: "ফিল্টাৰ",
    status_open: "খোলা",
    status_restricted: "নিয়ন্ত্ৰিত",
    status_degraded: "ক্ষতিগ্ৰস্ত",
    status_closed: "বন্ধ",
    role: "ভূমিকা",
    admin: "ৰাজ্য প্ৰশাসন",
    collector: "জিলা উপায়ুক্ত (DC)",
    logistics: "লজিষ্টিকছ চালক",
    inspector: "ক্ষেত্ৰ পৰিদৰ্শক (PWD)",
    sign_in: "প্ৰৱেশ কৰক",
    register: "পঞ্জীয়ন",
    back_to_map: "← মানচিত্ৰলৈ উভতক",
    one_tap_sos: "এছঅ'এছ সংকেত প্ৰেৰণ",
    launch_ar: "AR LiDAR মাপক",
    submit_report: "পদক্ষেপ ৫: প্ৰতিবেদন দাখিল"
  },
  bn: {
    app_title: "নেরালিস — উত্তর-পূর্ব লজিস্টিকস ইন্টেলিজেন্স",
    tagline: "উত্তর-পূর্ব অঞ্চল উন্নয়ন মন্ত্রক (MDoNER)",
    module_1: "পথ সুগমতা পর্যবেক্ষণ",
    module_2: "এআই রুট অপটিমাইজার",
    module_3: "যানবাহন ট্র্যাকিং ব্যবস্থা",
    module_4: "বিপর্যয় পূর্বাভাস (৭২ ঘণ্টা)",
    module_5: "বহুভাষিক সতর্কতা কেন্দ্র",
    module_6: "ফিল্ড রিপোর্টিং PWA",
    module_7: "কেন্দ্রীয় অ্যানালিটিক্স",
    module_8: "অফলাইন পরিষেবা",
    operations: "পরিচালনা",
    response: "সাড়া ও সতর্কতা",
    insights: "বিশ্লেষণ",
    reports_compliance: "প্রতিবেদন ও সম্মতি",
    parliament_report: "সংসদ / বিধায়ক রিপোর্ট",
    today_alerts: "সক্রিয় সতর্কতা",
    open_routes_pct: "উন্মুক্ত করিডোর",
    vehicles_tracked: "ট্র্যাক করা যানবাহন",
    pending_reports: "অমীমাংসিত রিপোর্ট",
    sync_status: "নেটওয়ার্ক মোড",
    online: "অনলাইন (5G)",
    low_2g: "ধীরগতির 2G",
    offline: "অফলাইন সক্রিয়",
    quick_search: "৮৯টি জেলা, মহাসড়ক বা সেতু খুঁজুন...",
    emergency_ticker: "সতর্কতা: তিস্তা ভ্যালি NH-10 বন্ধ। ব্রহ্মপুত্র নৌপথ রো-রো পরিষেবা সক্রিয়।",
    export_pdf: "পিডিএফ ডাউনলোড",
    export_excel: "এক্সেল ডাউনলোড",
    export_csv: "সিএসভি ডাউনলোড",
    filter: "ফিল্টার",
    status_open: "উন্মুক্ত",
    status_restricted: "নিয়ন্ত্রিত",
    status_degraded: "ক্ষতিগ্রস্ত",
    status_closed: "বন্ধ",
    role: "দায়িত্ব",
    admin: "রাজ্য প্রশাসন",
    collector: "জেলাশাসক (DM)",
    logistics: "পরিবহন অপারেটর",
    inspector: "ফিল্ড ইন্সপেক্টর",
    sign_in: "লগ ইন",
    register: "নিবন্ধন",
    back_to_map: "← মানচিত্রে ফিরুন",
    one_tap_sos: "স্যাটেলাইট এসওএস",
    launch_ar: "এআর লিডার চালু করুন",
    submit_report: "ধাপ ৫: রিপোর্ট জমা দিন"
  },
  mni: {
    app_title: "ꯅꯦꯔꯥꯂꯤꯁ — ꯑꯋꯥꯡ-ꯅꯣꯡꯄꯣꯛ ꯂꯣꯖꯤꯁ꯭ꯇꯤꯛꯁ",
    tagline: "ꯑꯋꯥꯡ ꯅꯣꯡꯄꯣꯛ ꯂꯝꯗꯝ ꯆꯥꯎꯈꯠ-ꯊꯧꯔꯥꯡ ꯃꯟꯠꯔꯥꯂꯌ (MDoNER)",
    module_1: "ꯂꯝꯕꯤ ꯌꯦꯡꯁꯤꯟꯕ",
    module_2: "AI ꯂꯝꯕꯤ ꯈꯪꯗꯣꯛꯄ",
    module_3: "ꯒꯥꯔꯤ ꯇ꯭ꯔꯦꯛ ꯇꯧꯕ",
    module_4: "ꯂꯝꯕꯤ ꯊꯤꯡꯖꯤꯟꯕ ꯄꯥꯎꯇꯥꯛ (꯷꯲ ꯄꯨꯡ)",
    module_5: "ꯂꯣꯟ ꯀꯌꯥꯒꯤ ꯆꯦꯛꯁꯤꯟ-ꯄꯥꯎ",
    module_6: "ꯐꯤꯜꯗ ꯔꯤꯄꯣꯔ꯭ꯇꯤꯡ PWA",
    module_7: "ꯑꯄꯨꯟꯕ ꯑꯦꯅꯥꯂꯥꯏꯇꯤꯛꯁ",
    module_8: "ꯑꯣꯐꯂꯥꯏꯟ ꯁꯤꯁ꯭ꯇꯦꯝ",
    operations: "ꯊꯕꯛ-ꯊꯧꯔꯝ",
    response: "ꯄꯥꯎꯈꯨꯝ ꯑꯃꯁꯨꯡ ꯄꯥꯎ",
    insights: "ꯅꯩꯅꯕ",
    reports_compliance: "ꯔꯤꯄꯣꯔ꯭ꯠ ꯑꯃꯁꯨꯡ ꯆꯠꯅ-ꯀꯥꯡꯂꯣꯟ",
    parliament_report: "ꯄꯥꯔꯂꯤꯌꯥꯃꯦꯟꯇ ꯔꯤꯄꯣꯔ꯭ꯠ",
    today_alerts: "ꯉꯁꯤꯒꯤ ꯆꯦꯛꯁꯤꯟ-ꯄꯥꯎ",
    open_routes_pct: "ꯍꯥꯡꯂꯤꯕ ꯂꯝꯕꯤ",
    vehicles_tracked: "ꯇ꯭ꯔꯦꯛ ꯇꯧꯔꯤꯕ ꯒꯥꯔꯤ",
    pending_reports: "ꯉꯥꯏꯔꯤꯕ ꯔꯤꯄꯣꯔ꯭ꯠ",
    sync_status: "ꯅꯦꯠꯋꯥꯔꯛ ꯃꯑꯣꯡ",
    online: "ꯑꯣꯟꯂꯥꯏꯟ (5G)",
    low_2g: "ꯇꯞꯄ 2G",
    offline: "ꯑꯣꯐꯂꯥꯏꯟ ꯑꯣꯏꯅ",
    quick_search: "ꯖꯤꯂꯥ ꯸꯹, ꯍꯥꯏꯋꯦ ꯅꯠꯇ꯭ꯔꯒ ꯊꯣꯡ ꯊꯤꯕ...",
    emergency_ticker: "ꯆꯦꯛꯁꯤꯟ-ꯄꯥꯎ: ꯇꯤꯁ꯭ꯇꯥ NH-10 ꯊꯤꯡꯖꯤꯜꯂꯦ। ꯏꯁꯤꯡ ꯂꯝꯕꯤ ꯔꯣ-ꯔꯣ ꯁꯔꯚꯤꯁ ꯆꯠꯂꯤ।",
    export_pdf: "PDF ꯂꯧꯊꯣꯛꯄ",
    export_excel: "Excel ꯂꯧꯊꯣꯛꯄ",
    export_csv: "CSV ꯂꯧꯊꯣꯛꯄ",
    filter: "ꯈꯅꯕ",
    status_open: "ꯍꯥꯡꯂꯦ",
    status_restricted: "ꯑꯊꯤꯡꯕ ꯂꯩ",
    status_degraded: "ꯁꯣꯛꯍꯜꯂꯦ",
    status_closed: "ꯊꯤꯡꯖꯤꯜꯂꯦ",
    role: "ꯊꯧꯗꯥꯡ",
    admin: "ꯁ꯭ꯇꯦꯠ ꯑꯦꯗꯃꯤꯟ",
    collector: "ꯗꯤꯁ꯭ꯇ꯭ꯔꯤꯛ ꯃꯦꯖꯤꯁ꯭ꯇ꯭ꯔꯦꯠ (DM)",
    logistics: "ꯄꯣꯠ-ꯆꯩ ꯄꯨꯕ",
    inspector: "ꯐꯤꯜꯗ ꯏꯟꯁꯄꯦꯛꯇꯔ",
    sign_in: "ꯆꯪꯕ",
    register: "ꯃꯤꯡ ꯆꯟꯕ",
    back_to_map: "← ꯃꯦꯞꯇ ꯍꯜꯂꯛꯄ",
    one_tap_sos: "ꯁꯦꯇꯦꯂꯥꯏꯠ SOS ꯊꯥꯕ",
    launch_ar: "AR LiDAR ꯍꯥꯡꯗꯣꯛꯎ",
    submit_report: "ꯁ꯭ꯇꯦꯞ ꯵: ꯔꯤꯄꯣꯔ꯭ꯠ ꯄꯤꯁꯤꯟꯕ"
  },
  khasi: {
    app_title: "NERALIS — North Eastern Logistics Intelligence",
    tagline: "Ministry of Development of North Eastern Region (MDoNER)",
    module_1: "Jingpeit Bniah ia ki Surok",
    module_2: "AI Route Optimizer",
    module_3: "Jingbud ia ki Kali (Fleet)",
    module_4: "Jingma Jingeh Surok (72 Kynta)",
    module_5: "Kynhun Maham Bun Ktien",
    module_6: "PWA Jingtip na Madan",
    module_7: "Central Analytics Dashboard",
    module_8: "Offline & Jingtei Surok",
    operations: "Ki Kam Surok",
    response: "Jingshim Khia & Jingmaham",
    insights: "Ka Jingbatai Bniah",
    reports_compliance: "Kaiphod & Ki Ain",
    parliament_report: "Kaiphod Sha Parliament",
    today_alerts: "Ki Jingmaham Mynta",
    open_routes_pct: "Ki Surok ba Plie",
    vehicles_tracked: "Ki Kali ba Bud",
    pending_reports: "Ki Kaiphod ba Sah",
    sync_status: "Network Mode",
    online: "Online (5G)",
    low_2g: "2G Network ba Slem",
    offline: "Offline ba Trei Kam",
    quick_search: "Wad ia ki 89 Districts, Surok bah lane ki Jingkieng...",
    emergency_ticker: "MAHAM: NH-10 Teesta Valley la khang. Ka Brahmaputra NW-2 Ro-Ro service ka trei kam.",
    export_pdf: "Pynmih PDF",
    export_excel: "Pynmih Excel",
    export_csv: "Pynmih CSV",
    filter: "Jied",
    status_open: "Plie",
    status_restricted: "Don Jingkhang",
    status_degraded: "Sniew",
    status_closed: "Khang",
    role: "Ka Kam",
    admin: "State Admin",
    collector: "District Collector (DC)",
    logistics: "Nongpyniaid Kali",
    inspector: "Field Inspector (PWD)",
    sign_in: "Rung",
    register: "Pynkyrteng",
    back_to_map: "← Leit Phai Sha Ka Map",
    one_tap_sos: "SATELLITE SOS BA MAR SYNDON",
    launch_ar: "Plie AR LiDAR",
    submit_report: "Step 5: Phah ia ka Kaiphod"
  },
  mizo: {
    app_title: "NERALIS — North Eastern Logistics Intelligence",
    tagline: "Ministry of Development of North Eastern Region (MDoNER)",
    module_1: "Kawng Leh Zin Kawng Endikna",
    module_2: "AI Kawng Thlan Felfaina",
    module_3: "Motor Chhui Zui Na (Fleet)",
    module_4: "Kawng Chhiatna Hrilhlawkna (72 Hrs)",
    module_5: "Tawng Hrang Hrang Alert",
    module_6: "PWA Hmun Hma Report",
    module_7: "Central Analytics Dashboard",
    module_8: "Offline & Resilience",
    operations: "Hna Thawh Dan",
    response: "Chhanna & Hriattirna",
    insights: "Thlirchianna",
    reports_compliance: "Report & Dan Zawm Dan",
    parliament_report: "Parliament / MLA Brief",
    today_alerts: "Alert Awm Mekte",
    open_routes_pct: "Kawng Tlang Theite",
    vehicles_tracked: "Motor Chhui Mekte",
    pending_reports: "Report La Tifelhte",
    sync_status: "Network Awm Dan",
    online: "Online (5G / Fiber)",
    low_2g: "2G Chaklo",
    offline: "Offline Hna Thawh Mek",
    quick_search: "District 89, kawngpui emaw lei zawng rawh...",
    emergency_ticker: "HRINGTIRNA: NH-10 Teesta Valley khar a ni. Brahmaputra NW-2 Ro-Ro lawng hman mek a ni.",
    export_pdf: "PDF Laphhuak",
    export_excel: "Excel Laphhuak",
    export_csv: "CSV Laphhuak",
    filter: "Thlitfimna",
    status_open: "Inhawng",
    status_restricted: "Khar Chen",
    status_degraded: "Chhia",
    status_closed: "Khar",
    role: "Hna Chelh",
    admin: "State Admin (MDoNER)",
    collector: "District Magistrate (DM)",
    logistics: "Logistics Operator",
    inspector: "Field Inspector (PWD)",
    sign_in: "Lut Rawh",
    register: "Inziah Luhna",
    back_to_map: "← Map-ah Kir Rawh",
    one_tap_sos: "SATELLITE SOS TI NUN",
    launch_ar: "AR LiDAR Hmet Chhuak Rawh",
    submit_report: "Step 5: Report Thehluh Rawh"
  },
  nagamese: {
    app_title: "NERALIS — North Eastern Logistics Intelligence",
    tagline: "Ministry of Development of North Eastern Region (MDoNER)",
    module_1: "Rasta Bhal Asey Ki Nai Saikena",
    module_2: "AI Rasta Banaboley System",
    module_3: "Gari Tracking Aru Telemetry",
    module_4: "Landslide Hober Predict (72 Ghanta)",
    module_5: "Bisi Language laga Alert Center",
    module_6: "Field Reporting PWA App",
    module_7: "Central Analytics Dashboard",
    module_8: "Offline & Network System",
    operations: "Kaam Kora Section",
    response: "Response & Alert Khan",
    insights: "Data Saikena",
    reports_compliance: "Report & Niyom Khan",
    parliament_report: "Parliament / MLA Report",
    today_alerts: "Chuli Thaka Alert",
    open_routes_pct: "Khula Rasta Khan",
    vehicles_tracked: "Track Kora Gari",
    pending_reports: "Pending Report Khan",
    sync_status: "Network Mode",
    online: "Online (5G / High Speed)",
    low_2g: "Slow 2G Network",
    offline: "Offline Kaam Kori Asey",
    quick_search: "89 Districts, Highway, Bridge bhal pora bisari lobi...",
    emergency_ticker: "ALERT: NH-10 Teesta Valley bondho korishey. Brahmaputra Ro-Ro ship service chuli asey.",
    export_pdf: "PDF Banabi",
    export_excel: "Excel Banabi",
    export_csv: "CSV Banabi",
    filter: "Filter",
    status_open: "Khula",
    status_restricted: "Advisory",
    status_degraded: "Kharab",
    status_closed: "Bondho",
    role: "Role",
    admin: "State Admin",
    collector: "Deputy Commissioner (DC)",
    logistics: "Transport Operator",
    inspector: "Field Officer (PWD)",
    sign_in: "Sign In",
    register: "Register",
    back_to_map: "← Map te Jabi",
    one_tap_sos: "ONE-TAP SATELLITE SOS",
    launch_ar: "AR LiDAR Scanner Khulibi",
    submit_report: "Step 5: Report Submit Koribi"
  },
  ne: {
    app_title: "नेरालिस — उत्तर पूर्वी रसद बौद्धिकता",
    tagline: "उत्तर पूर्वी क्षेत्र विकास मन्त्रालय (MDoNER)",
    module_1: "सडक पहुँच अनुगमन",
    module_2: "एआई मार्ग अनुकूलक",
    module_3: "सवारी साधन ट्र्याकिङ",
    module_4: "पहिरो तथा अवरोध पूर्वानुमान (७२ घण्टा)",
    module_5: "बहुभाषिक अलर्ट केन्द्र",
    module_6: "फिल्ड रिपोर्टिङ PWA",
    module_7: "केन्द्रीय विश्लेषणात्मक ड्यासबोर्ड",
    module_8: "अफलाइन तथा नेटवर्क प्रणाली",
    operations: "सञ्चालन कार्यहरू",
    response: "प्रतिक्रिया तथा अलर्ट",
    insights: "विश्लेषण र अन्तर्दृष्टि",
    reports_compliance: "प्रतिवेदन र अनुपालन",
    parliament_report: "संसद / विधायक प्रतिवेदन",
    today_alerts: "सक्रिय अलर्टहरू",
    open_routes_pct: "खुला सडकहरू",
    vehicles_tracked: "ट्र्याक गरिएका सवारी",
    pending_reports: "बाँकी प्रतिवेदनहरू",
    sync_status: "नेटवर्क मोड",
    online: "अनलाइन (5G)",
    low_2g: "सुस्त 2G नेटवर्क",
    offline: "अफलाइन सक्रिय",
    quick_search: "८९ जिल्लाहरू, राजमार्ग वा पुलहरू खोज्नुहोस्...",
    emergency_ticker: "चेतावनी: तीस्ता उपत्यका NH-10 २९ माइलमा बन्द छ। ब्रह्मपुत्र जलमार्ग रो-रो सेवा सञ्चालनमा।",
    export_pdf: "PDF निर्यात",
    export_excel: "Excel निर्यात",
    export_csv: "CSV निर्यात",
    filter: "फिल्टर",
    status_open: "खुला",
    status_restricted: "प्रतिबन्धित",
    status_degraded: "जीर्ण",
    status_closed: "बन्द",
    role: "भूमिका",
    admin: "राज्य प्रशासन",
    collector: "जिल्ला अधिकारी (DM)",
    logistics: "रसद सञ्चालक",
    inspector: "फिल्ড निरीक्षक",
    sign_in: "लग इन",
    register: "दर्ता",
    back_to_map: "← नक्सामा फर्कनुहोस्",
    one_tap_sos: "स्याटेलाइट आपतकालीन एसओएस",
    launch_ar: "एआर लिडार सुरु गर्नुहोस्",
    submit_report: "चरण ५: रिपोर्ट पेश गर्नुहोस्"
  }
};

interface LanguageContextType {
  currentLanguage: LanguageCode;
  setLanguage: (lang: LanguageCode) => void;
  t: (key: string) => string;
  languages: LanguageInfo[];
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [currentLanguage, setCurrentLanguageState] = useState<LanguageCode>(() => {
    try {
      const saved = localStorage.getItem('neralis_language');
      if (saved && SUPPORTED_LANGUAGES.some((l) => l.code === saved)) {
        return saved as LanguageCode;
      }
    } catch {
      // ignore
    }
    return 'en';
  });

  const setLanguage = (lang: LanguageCode) => {
    setCurrentLanguageState(lang);
    try {
      localStorage.setItem('neralis_language', lang);
    } catch {
      // ignore
    }
  };

  const t = (key: string): string => {
    return UI_STRINGS[currentLanguage]?.[key] || UI_STRINGS['en']?.[key] || key;
  };

  return (
    <LanguageContext.Provider value={{ currentLanguage, setLanguage, t, languages: SUPPORTED_LANGUAGES }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const ctx = useContext(LanguageContext);
  if (!ctx) {
    throw new Error('useLanguage must be used within LanguageProvider');
  }
  return ctx;
};
