import React, { createContext, useContext, useState } from 'react';

export type LanguageCode = 'en' | 'hi' | 'as' | 'bn' | 'mni' | 'khasi' | 'mizo' | 'nagamese' | 'ne';

export interface LanguageInfo {
  code: LanguageCode;
  label: string;
  native: string;
  states: string;
  script: string;
}

export const SUPPORTED_LANGUAGES: LanguageInfo[] = [
  { code: 'en', label: 'English', native: 'English', states: 'All 8 States (Official)', script: 'Latin' },
  { code: 'hi', label: 'Hindi', native: 'हिन्दी', states: 'All 8 States (Fallback)', script: 'Devanagari' },
  { code: 'as', label: 'Assamese', native: 'অসমীয়া', states: 'Assam', script: 'Bengali-Assamese' },
  { code: 'bn', label: 'Bengali', native: 'বাংলা', states: 'Tripura, Assam (Barak)', script: 'Bengali' },
  { code: 'mni', label: 'Meitei (Manipuri)', native: 'ꯃꯩꯇꯩꯂꯣꯟ', states: 'Manipur', script: 'Meitei Mayek' },
  { code: 'khasi', label: 'Khasi / Garo', native: 'Khasi / Garo', states: 'Meghalaya', script: 'Latin' },
  { code: 'mizo', label: 'Mizo', native: 'Mizo ṭawng', states: 'Mizoram', script: 'Latin' },
  { code: 'nagamese', label: 'Nagamese', native: 'Nagamese', states: 'Nagaland', script: 'Latin' },
  { code: 'ne', label: 'Nepali', native: 'नेपाली', states: 'Sikkim', script: 'Devanagari' },
];

const UI_STRINGS: Record<LanguageCode, Record<string, string>> = {
  en: {
    app_title: "NERALIS — North Eastern Logistics Intelligence",
    tagline: "Ministry of Development of North Eastern Region (MDoNER)",
    module_1: "Accessibility Monitoring",
    module_2: "AI Route Optimizer",
    module_3: "Vehicle & Fleet Tracking",
    module_4: "Predictive Disruption (72h)",
    module_5: "Multilingual Alert Center",
    module_6: "Field Reporting PWA",
    module_7: "Central Analytics Dashboard",
    module_8: "Offline & Resilience",
    parliament_report: "Parliament / MLA Brief",
    today_alerts: "Active Alerts",
    open_routes_pct: "Open Corridors",
    vehicles_tracked: "Tracked Fleet",
    pending_reports: "Pending Reports",
    sync_status: "Network Mode",
    online: "Online (5G / Fiber)",
    low_2g: "Low 2G Bandwidth",
    offline: "Offline Storage Active",
    quick_search: "Search 89 NER districts, highways, or bridge sensors...",
    emergency_ticker: "ALERT: Teesta Valley NH-10 closed at 29th Mile. Brahmaputra NW-2 Ro-Ro barge active for essential medical transport.",
    export_pdf: "Export PDF",
    export_excel: "Export Excel",
    export_csv: "Export CSV",
    filter: "Filter",
    status_open: "Open",
    status_restricted: "Restricted",
    status_degraded: "Degraded",
    status_closed: "Closed",
    role: "User Role",
    admin: "State Admin (MDoNER)",
    collector: "District Collector / DM",
    logistics: "Logistics Operator",
    inspector: "Field Inspector / PWD"
  },
  hi: {
    app_title: "नेरालिस — उत्तर पूर्वी लॉजिस्टिक्स इंटेलिजेंस",
    tagline: "उत्तर पूर्वी क्षेत्र विकास मंत्रालय (MDoNER)",
    module_1: "सड़क सुलभता निगरानी",
    module_2: "एआई रूट ऑप्टिमाइज़र",
    module_3: "वाहन व बेड़ा ट्रैकिंग",
    module_4: "पूर्वानुमान व्यवधान (72 घंटे)",
    module_5: "बहुभाषी अलर्ट केंद्र",
    module_6: "फील्ड रिपोर्टिंग PWA",
    module_7: "केंद्रीय एनालिटिक्स डैशबोर्ड",
    module_8: "ऑफलाइन व कनेक्टिविटी",
    parliament_report: "संसद / विधायक रिपोर्ट",
    today_alerts: "सक्रिय अलर्ट",
    open_routes_pct: "खुले मार्ग",
    vehicles_tracked: "सक्रिय वाहन",
    pending_reports: "लंबित रिपोर्ट",
    sync_status: "नेटवर्क मोड",
    online: "ऑनलाइन (5G)",
    low_2g: "धीमा 2G नेटवर्क",
    offline: "ऑफलाइन सक्रिय",
    quick_search: "89 पूर्वोत्तर जिलों, राजमार्गों या पुलों को खोजें...",
    emergency_ticker: "सूचना: तीस्ता घाटी NH-10 29वें मील पर बंद। ब्रह्मपुत्र जलमार्ग रो-रो सेवा आवश्यक दवाओं हेतु चालू।",
    export_pdf: "पीडीएफ निर्यात",
    export_excel: "एक्सेल निर्यात",
    export_csv: "सीएसवी निर्यात",
    filter: "फ़िल्टर",
    status_open: "खुला",
    status_restricted: "प्रतिबंधित",
    status_degraded: "खराब",
    status_closed: "बंद",
    role: "भूमिका",
    admin: "राज्य प्रशासन (MDoNER)",
    collector: "जिलाधिकारी (DM)",
    logistics: "लॉजिस्टिक्स ऑपरेटर",
    inspector: "फील्ड इंस्पेक्टर (PWD)"
  },
  as: {
    app_title: "নেৰালিচ — উত্তৰ-পূব লজিষ্টিকছ ইন্টেলিজেন্স",
    tagline: "উত্তৰ-পূব অঞ্চল উন্নয়ন মন্ত্ৰালয় (MDoNER)",
    module_1: "পথ সুগমতা নিৰীক্ষণ",
    module_2: "AI পথ অনুকূলকৰণ",
    module_3: "যান-বাহন ট্ৰেকিং",
    module_4: "বাধাৰ পূৰ্বানুমান (৭২ ঘণ্টা)",
    module_5: "বহুভাষিক সতৰ্কতা কেন্দ্ৰ",
    module_6: "ক্ষেত্ৰ প্ৰতিবেদন PWA",
    module_7: "কেন্দ্ৰীয় বিশ্লেষণ ডেশ্ববৰ্ড",
    module_8: "অফলাইন আৰু নেটৱৰ্ক",
    parliament_report: "সংসদ / বিধায়ক প্ৰতিবেদন",
    today_alerts: "সক্ৰিয় সতৰ্কতা",
    open_routes_pct: "খোলা পথ",
    vehicles_tracked: "ট্ৰেক কৰা গাড়ী",
    pending_reports: "বাকী থকা প্ৰতিবেদন",
    sync_status: "নেটৱৰ্ক অৱস্থা",
    online: "অনলাইন (5G)",
    low_2g: "ধীৰ 2G সংযোগ",
    offline: "অফলাইন সক্ৰিয়",
    quick_search: "৮৯খন জিলা, ঘাইপথ বা দলং বিচাৰক...",
    emergency_ticker: "সতৰ্কতা: তিস্তা উপত্যকা NH-10 বন্ধ। ব্ৰহ্মপুত্ৰ ৰো-ৰো জাহাজ সেৱা সক্ৰিয়।",
    export_pdf: "PDF ৰপ্তানি",
    export_excel: "Excel ৰপ্তানি",
    export_csv: "CSV ৰপ্তানি",
    filter: "ফিল্টাৰ",
    status_open: "খোলা",
    status_restricted: "নিয়ন্ত্ৰিত",
    status_degraded: "ক্ষতিগ্ৰস্ত",
    status_closed: "বন্ধ",
    role: "ভূমিকা",
    admin: "ৰাজ্য প্ৰশাসন",
    collector: "জিলা উপায়ুক্ত (DC)",
    logistics: "লজিষ্টিকছ চালক",
    inspector: "ক্ষেত্ৰ পৰিদৰ্শক (PWD)"
  },
  bn: {
    app_title: "নেরালিস — উত্তর-পূর্ব লজিস্টিকস ইন্টেলিজেন্স",
    tagline: "উত্তর-পূর্ব অঞ্চল উন্নয়ন মন্ত্রক (MDoNER)",
    module_1: "পথ সুগমতা পর্যবেক্ষণ",
    module_2: "এআই রুট অপটিমাইজার",
    module_3: "যানবাহন ট্র্যাকিং ব্যবস্থা",
    module_4: "বিপর্যয় পূর্বাভাস (৭২ ঘণ্টা)",
    module_5: "বহুভাষিক সতর্কতা কেন্দ্র",
    module_6: "ফিল্ড রিপোর্টিং PWA",
    module_7: "কেন্দ্রীয় অ্যানালিটিক্স",
    module_8: "অফলাইন পরিষেবা",
    parliament_report: "সংসদ / বিধায়ক রিপোর্ট",
    today_alerts: "সক্রিয় সতর্কতা",
    open_routes_pct: "উন্মুক্ত করিডোর",
    vehicles_tracked: "ট্র্যাক করা যানবাহন",
    pending_reports: "অমীমাংসিত রিপোর্ট",
    sync_status: "নেটওয়ার্ক মোড",
    online: "অনলাইন (5G)",
    low_2g: "ধীরগতির 2G",
    offline: "অফলাইন সক্রিয়",
    quick_search: "৮৯টি জেলা, মহাসড়ক বা সেতু সন্ধান করুন...",
    emergency_ticker: "জরুরি: তিস্তা ভ্যালি NH-10 বন্ধ। ব্রহ্মপুত্র নৌরুট রো-রো সেবা চালু রয়েছে।",
    export_pdf: "PDF সংরক্ষণ",
    export_excel: "Excel সংরক্ষণ",
    export_csv: "CSV সংরক্ষণ",
    filter: "ফিল্টার",
    status_open: "উন্মুক্ত",
    status_restricted: "সীমিত",
    status_degraded: "ক্ষতিগ্রস্ত",
    status_closed: "বন্ধ",
    role: "দায়িত্ব",
    admin: "রাজ্য প্রশাসন",
    collector: "জেলাশাসক (DM)",
    logistics: "লজিস্টিকস অপারেটর",
    inspector: "ফিল্ড ইন্সপেক্টর"
  },
  mni: {
    app_title: "ꯅꯦꯔꯥꯂꯤꯁ — ꯑꯋꯥꯡ ꯅꯣꯡꯄꯣꯛ ꯂꯣꯖꯤꯁ꯭ꯇꯤꯛꯁ",
    tagline: "ꯃꯤꯅꯤꯁ꯭ꯇ꯭ꯔꯤ ꯑꯣꯐ ꯗꯤꯕꯦꯂꯞꯃꯦꯟꯇ ꯑꯣꯐ ꯑꯦꯟ.ꯏ.ꯑꯥꯔ (MDoNER)",
    module_1: "ꯂꯝꯕꯤ ꯌꯦꯡꯁꯤꯟꯕ",
    module_2: "AI ꯂꯝꯕꯤ ꯈꯟꯕ",
    module_3: "ꯒꯥꯔꯤ ꯇ꯭ꯔꯦꯀꯤꯡ",
    module_4: "ꯈꯨꯗꯣꯡꯊꯤꯕ ꯄꯥꯎꯗꯝ (ꯄꯨꯡ ꯷꯲)",
    module_5: "ꯂꯣꯟ ꯀꯌꯥꯒꯤ ꯆꯦꯀꯁꯤꯟꯋꯥ",
    module_6: "ꯐꯤꯜꯗ ꯔꯤꯄꯣꯔ꯭ꯇꯤꯡ PWA",
    module_7: "ꯁꯦꯟꯇ꯭ꯔꯦꯜ ꯗꯦꯁꯕꯣꯔ꯭ꯗ",
    module_8: "ꯑꯣꯐꯂꯥꯏꯟ ꯁꯤꯁ꯭ꯇꯦꯝ",
    parliament_report: "ꯄꯥꯔꯂꯤꯌꯥꯃꯦꯟꯇ ꯔꯤꯄꯣꯔ꯭ꯇ",
    today_alerts: "ꯆꯦꯀꯁꯤꯟꯋꯥꯁꯤꯡ",
    open_routes_pct: "ꯍꯥꯡꯗꯣꯛꯂꯕ ꯂꯝꯕꯤ",
    vehicles_tracked: "ꯇ꯭ꯔꯦꯛ ꯇꯧꯔꯕ ꯒꯥꯔꯤ",
    pending_reports: "ꯂꯩꯔꯤꯕ ꯔꯤꯄꯣꯔ꯭ꯇꯁꯤꯡ",
    sync_status: "ꯅꯦꯠꯋꯥꯔ꯭ꯛ",
    online: "ꯑꯣꯟꯂꯥꯏꯟ (5G)",
    low_2g: "ꯇꯞꯄ 2G",
    offline: "ꯑꯣꯐꯂꯥꯏꯟ",
    quick_search: "ꯗꯤꯁ꯭ꯇ꯭ꯔꯤꯛ ꯸꯹, ꯍꯥꯏꯋꯦ ꯊꯤꯕ...",
    emergency_ticker: "ꯆꯦꯀꯁꯤꯟꯋꯥ: NH-10 ꯇꯤꯁ꯭ꯇꯥ ꯚꯦꯂꯤ ꯂꯝꯕꯤ ꯊꯤꯡꯖꯤꯟꯈ꯭ꯔꯦ꯫",
    export_pdf: "PDF ꯂꯧꯊꯣꯛꯎ",
    export_excel: "Excel ꯂꯧꯊꯣꯛꯎ",
    export_csv: "CSV ꯂꯧꯊꯣꯛꯎ",
    filter: "ꯈꯟꯕ",
    status_open: "ꯍꯥꯡꯂꯦ",
    status_restricted: "ꯑꯀꯛꯅꯕ",
    status_degraded: "ꯁꯣꯛꯍꯜꯂꯦ",
    status_closed: "ꯊꯤꯡꯖꯤꯜꯂꯦ",
    role: "ꯊꯧꯗꯥꯡ",
    admin: "ꯁ꯭ꯇꯦꯠ ꯑꯦꯗꯃꯤꯟ",
    collector: "ꯗꯤꯁ꯭ꯇ꯭ꯔꯤꯛ ꯃꯦꯖꯤꯁ꯭ꯇ꯭ꯔꯦꯠ (DM)",
    logistics: "ꯂꯣꯖꯤꯁ꯭ꯇꯤꯛꯁ",
    inspector: "ꯐꯤꯜꯗ ꯏꯟꯁꯄꯦꯛꯇꯔ"
  },
  khasi: {
    app_title: "NERALIS — Logistics Intelligence ka Shatei Lam Mihngi",
    tagline: "Ministry of Development of North Eastern Region (MDoNER)",
    module_1: "Jingpeit Bniah ia ki Surok",
    module_2: "AI Route Optimizer",
    module_3: "Jingbuddien ia ki Kali",
    module_4: "Jingmaham Jingeh (72 kynta)",
    module_5: "Kynhun Maham Bun Ktien",
    module_6: "Field Reporting PWA",
    module_7: "Central Analytics Dashboard",
    module_8: "Offline & Resilience",
    parliament_report: "Parliament Brief",
    today_alerts: "Ki Jingmaham",
    open_routes_pct: "Surok ba Plie",
    vehicles_tracked: "Kali ba Buddien",
    pending_reports: "Report ba Sah",
    sync_status: "Network Mode",
    online: "Online (5G)",
    low_2g: "2G ba Swai",
    offline: "Offline Active",
    quick_search: "Wad 89 districts, surok heh, bridge...",
    emergency_ticker: "MAHAM: NH-10 Teesta Valley la khang. Brahmaputra NW-2 barge plie.",
    export_pdf: "Export PDF",
    export_excel: "Export Excel",
    export_csv: "Export CSV",
    filter: "Filter",
    status_open: "Plie",
    status_restricted: "Advisory",
    status_degraded: "Sniew",
    status_closed: "Khang",
    role: "Kam",
    admin: "State Admin",
    collector: "Deputy Commissioner (DC)",
    logistics: "Logistics Operator",
    inspector: "Field Inspector"
  },
  mizo: {
    app_title: "NERALIS — Chhim Chhak Logistics Hriattirna",
    tagline: "Ministry of Development of North Eastern Region (MDoNER)",
    module_1: "Kawng dinhmun Enzuina",
    module_2: "AI Kawng Thlan Chhuahna",
    module_3: "Motor Chhui Zui Na",
    module_4: "Chhiatrupna Hrilhlawkna (72h)",
    module_5: "Ṭawng Hrang Hrang Alert",
    module_6: "Field Report Thehluhna",
    module_7: "Central Analytics Dashboard",
    module_8: "Offline & Resilience",
    parliament_report: "Parliament / MLA Brief",
    today_alerts: "Alert Awm Mek",
    open_routes_pct: "Kawng Tlang Thei",
    vehicles_tracked: "Motor Chhui Mek",
    pending_reports: "Report Thlen Hmabak",
    sync_status: "Network Dinhmun",
    online: "Online (5G)",
    low_2g: "2G Muang",
    offline: "Offline Hman Mek",
    quick_search: "NER district 89, kawngpui, lei zawng rawh...",
    emergency_ticker: "VAU KHANNA: NH-10 Teesta kawng khar a ni. Brahmaputra tuilian lai hian lawng hman theih a ni.",
    export_pdf: "PDF Download",
    export_excel: "Excel Download",
    export_csv: "CSV Download",
    filter: "Filter",
    status_open: "Hawn",
    status_restricted: "Fimkhur",
    status_degraded: "Chhe Deuh",
    status_closed: "Khar",
    role: "Hna Chelh",
    admin: "State Admin",
    collector: "District Magistrate (DM)",
    logistics: "Logistics Operator",
    inspector: "Field Inspector"
  },
  nagamese: {
    app_title: "NERALIS — North East Logistics System",
    tagline: "Ministry of Development of North Eastern Region (MDoNER)",
    module_1: "Rasta Condition Saikena Thaka",
    module_2: "AI Rasta Chunibole Engine",
    module_3: "Gaari Tracking System",
    module_4: "Landslide Risk Khabar (72 ghanta)",
    module_5: "Bisi Bhasha laga Alert Center",
    module_6: "Field Report Mobile App",
    module_7: "Main Control Dashboard",
    module_8: "Offline Support",
    parliament_report: "Parliament / MLA Report",
    today_alerts: "Aji laga Alerts",
    open_routes_pct: "Khula Rasta %",
    vehicles_tracked: "Track kora Gaari",
    pending_reports: "Pending Reports",
    sync_status: "Network Mode",
    online: "Online (5G)",
    low_2g: "Slow 2G",
    offline: "Offline Choli asey",
    quick_search: "89 districts, road, bridge khan bisaribi...",
    emergency_ticker: "ALERT: Teesta Valley NH-10 rasta bondho ase. Brahmaputra nodi barge khula ase dawa pathabole.",
    export_pdf: "PDF Banabi",
    export_excel: "Excel Banabi",
    export_csv: "CSV Banabi",
    filter: "Filter",
    status_open: "Khula",
    status_restricted: "Advisory",
    status_degraded: "Kharab",
    status_closed: "Bondho",
    role: "Role",
    admin: "State Admin",
    collector: "Deputy Commissioner (DC)",
    logistics: "Transport Operator",
    inspector: "Field Officer (PWD)"
  },
  ne: {
    app_title: "नेरालिस — उत्तर पूर्वी रसद बौद्धिकता",
    tagline: "उत्तर पूर्वी क्षेत्र विकास मन्त्रालय (MDoNER)",
    module_1: "सडक पहुँच अनुगमन",
    module_2: "एआई मार्ग अनुकूलक",
    module_3: "सवारी साधन ट्र्याकिङ",
    module_4: "पहिरो तथा अवरोध पूर्वानुमान (७२ घण्टा)",
    module_5: "बहुभाषिक अलर्ट केन्द्र",
    module_6: "फिल्ड रिपोर्टिङ PWA",
    module_7: "केन्द्रीय विश्लेषणात्मक ड्यासबोर्ड",
    module_8: "अफलाइन तथा नेटवर्क प्रणाली",
    parliament_report: "संसद / विधायक प्रतिवेदन",
    today_alerts: "सक्रिय अलर्टहरू",
    open_routes_pct: "खुला सडकहरू",
    vehicles_tracked: "ट्र्याक गरिएका सवारी",
    pending_reports: "बाँकी प्रतिवेदनहरू",
    sync_status: "नेटवर्क मोड",
    online: "अनलाइन (5G)",
    low_2g: "सुस्त 2G नेटवर्क",
    offline: "अफलाइन सक्रिय",
    quick_search: "८९ जिल्लाहरू, राजमार्ग वा पुलहरू खोज्नुहोस्...",
    emergency_ticker: "चेतावनी: तीस्ता उपत्यका NH-10 २९ माइलमा बन्द छ। ब्रह्मपुत्र जलमार्ग रो-रो सेवा सञ्चालनमा।",
    export_pdf: "PDF निर्यात",
    export_excel: "Excel निर्यात",
    export_csv: "CSV निर्यात",
    filter: "फिल्टर",
    status_open: "खुला",
    status_restricted: "प्रतिबन्धित",
    status_degraded: "जीर्ण",
    status_closed: "बन्द",
    role: "भूमिका",
    admin: "राज्य प्रशासन",
    collector: "जिल्ला अधिकारी (DM)",
    logistics: "रसद सञ्चालक",
    inspector: "फिल्ड निरीक्षक"
  }
};

interface LanguageContextType {
  currentLanguage: LanguageCode;
  setLanguage: (lang: LanguageCode) => void;
  t: (key: string) => string;
  languages: LanguageInfo[];
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [currentLanguage, setCurrentLanguage] = useState<LanguageCode>('en');

  const t = (key: string): string => {
    return UI_STRINGS[currentLanguage]?.[key] || UI_STRINGS['en']?.[key] || key;
  };

  return (
    <LanguageContext.Provider value={{ currentLanguage, setLanguage: setCurrentLanguage, t, languages: SUPPORTED_LANGUAGES }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const ctx = useContext(LanguageContext);
  if (!ctx) {
    throw new Error('useLanguage must be used within LanguageProvider');
  }
  return ctx;
};
